apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-gateway
  template:
    metadata:
      labels:
        app: spring-cloud-gateway
    spec:
      containers:
        - name: spring-cloud-gateway
          image: 171312460935.dkr.ecr.ap-southeast-1.amazonaws.com/mall-gateway:latest
          ports:
            - containerPort: 8080
