apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-gateway-service
spec:
  type: NodePort
  ports:
    - port: 3737
      targetPort: 3737
      nodePort: 32000
  selector:
    app: spring-cloud-gateway
